---
title: "data_cleaning"
author: "Thalie Emond"
date: "22/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(psych)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(remotes)
library(png)
library(viridisLite)
library(viridis)
#library(likert)
#library(plotly)
#library(maptools)
#library(doBy)
#library(gganimate)
#library(gpclib)
#gpclibPermit()
library(readxl)
library(stringr)
library(kableExtra)
library(magick)
library(tinytex)

getOption()
```

## GTD
```{r downsize, echo=FALSE}
gtdb70_19 <- read_xlsx("globalterrorismdb_0221dist.xlsx", )


gtdb_filtered <- gtdb70_19 %>%
  filter(country == "74" | country == "214", between(iyear, 2007, 2019)) %>% # Georgia (74), Ukraine (214)
  select(iyear, imonth, iday, country_txt, provstate, city, latitude, 
         location, summary, crit1, crit2, crit3, 
         attacktype1, attacktype1_txt, targtype1,
         targtype1_txt, targtype2, targtype2_txt, targtype3, targtype3_txt,
         corp1, weaptype1, weaptype1_txt, gsubname, guncertain1, individual,
         nwound, nkill, nhostkid, kidhijcountry, ndays, nreleased, INT_LOG,
         INT_MISC, INT_IDEO, INT_ANY, scite1, scite2, scite3, dbsource)

## from github

gtdb_filtered$iday <- as.integer(gsub(0, 1, gtdb_filtered$iday))

# Create a new variable "idate"
gtdb_filtered$idate <- as.Date(paste0(gtdb_filtered$iyear,
                       stringr::str_pad(as.character(gtdb_filtered$imonth), width = 2, side = "left", pad = "0"),
                       stringr::str_pad(as.character(gtdb_filtered$iday), width = 2, side = "left", pad = "0")), "%Y%m%d")

## saving 1st version

save(gtdb_filtered, file = "gtdb_ver0323.RData")

## 2 ver. compressing data: casaulties by day
gtdb_filtered2 <- gtdb_filtered %>%
  group_by(idate, country_txt) %>%
  summarize(nkill = sum(nkill, na.rm = T), nwound = sum(nwound, na.rm = T))


```
```{r test SQL}

```



