---
title: |
 | \vspace{3cm} Book Review: _The Red Mirror: Putin’s Leadership and Russia’s Insecure Identity_
 | \vspace{4cm}
author: " "
header-includes:
    - \usepackage{setspace}\doublespacing
date: "April 27, 2022"
output: 
  pdf_document:
    toc: FALSE
  indent: true
subtitle: | 
 | \vspace{1.5cm} Thalie Emond (260927077)
 | \vspace{1.5cm} POLI 524: Political Development in Europe
 | \vspace{1.5cm} Department of Political Science, McGill University
 | \vspace{1.5cm} Mr Philip-Emmanuel Aubry
geometry: left=2.5cm,right=2.5cm,top=2cm,bottom=2cm

---
\pagenumbering{gobble}
\setlength\parindent{24pt}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
library(tinytex) 
```

\newpage

\pagenumbering{arabic}

# Navigating a House of Mirrors: Imagined Nationhood in post-Soviet Russia

### INTRODUCTION


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This book review will critically analyze _The Red Mirror: Putin’s Leadership and Russia’s Insecure Identity_ by Gulnaz Sharafutdinova. Sharafutdinova’s book disentangles the fantastical nature of post-Soviet Russian nationalism and identity politics by using analogies and elements borrowed from the famed tale Through the Glass Looking-in. These analogies help readers who may not be well versed in post-Soviet studies or social psychology in authoritarian regimes, clouding self-awareness capabilities to understand the experience of surviving in authoritarian regimes. This paper aims to explore the dialectical scheme that Sharafutdinova uses along various methodological tools, such as empirical survey analysis and interpretivist approaches, to explain how identity politics, collective trauma, and Russia’s very one Newspeak play out in the Russian case. To start off, this paper will briefly summarize the main arguments that Sharafutdinova conveys in her book. It will then lay out the theoretical frameworks which she applies in her conceptualization of Russia’s collective identity and its evolution, while drawing parallels with the works of Benedict Anderson (1991). Next, it will refer to other nationalism and social identity theory scholars. Those authors have also looked into the peculiar case of Russian group identity in and outside of Russia, refining a little bit Sharafutdinova’s explanatory framework. Last, it will discuss the academic contribution of the book in the study of identity politics and nationalism at large. This paper argues that Gulnaz Sharafutdinova’s _The Red Mirror_ offers great insight on the intricate ways psychological and social structures influence nationalism, laying meaningful groundwork for nationalism and post-Soviet studies. 

To start, this paper will briefly summarize the main arguments that Sharafutdinova conveys in her book. Then, it will lay out the theoretical frameworks that she applies in her analysis of the evolution of Russia’s collective identity, while drawing parallels with the works of Benedict Anderson (1991), Linda Colley (2009), Hudson Meadwell (2020), and Timur Kuran (2017). Next, it will bring in other scholars, such as Stephen Saideman (2008) and Michail A. Alexseev (2016) that have also looked into the peculiar case of Russian group identity in and outside of Russia, refining a little bit Sharafutdinova’s explanatory framework. Last, it will discuss the academic contribution of the book in the study of identity politics and nationalism at large. This paper argues that Gulnaz Sharafutdinova‘s _The Red Mirror_ offers great insight on the intricate ways psychological and social structures influence nationalism, laying meaningful groundwork for nationalism studies as well as Western-based post-Soviet studies.
 
### BACKGROUND


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sharafutdinova (2020) begins her book detailing the intersection between Soviet and Russian national identities from the inception of modern-day Russia until 2020, giving context to her subsequent psychological and sociological examinations of group identification and behaviour. Divided in three parts, each of which are equally important to understanding Russian nationalism, _The Red Mirror_ starts with a fast-paced overview of the social and political environment that the United Socialist Soviet Republic (USSR) rests before and after its dissolution in 1991. That first section of the book allows readers who may not have ties to the USSR through relatives or friends to make sense of the emotional baggage that Russian people have carried from the Soviet collapse. Not only does it contain clearly outlined arguments, it also prefaces them so that readers can fully comprehend her explanations through the Russian population and her perspectives. For example, the roots of Russia’s insecure identity vis-à-vis its neighbours in the West, and to some extent, the so-called Third World, can be traced back to the social engineering of the USSR under Stalin in order to consolidate a multiethnic state adhering to Marxist-Leninist ideology (44). Thus, primary and secondary schooling facilitated the indoctrination of populations in the USSR with Soviet ideals, ensuring a common culture from which derived political loyalty. State legitimacy in the USSR, however, was based on two forms of validation. External validation rested on the Russian international reputation as a superpower, whereas internal validation comprised modes of group identification that enabled the population to distinguish themselves from the “other”. According to Sharafutdinova, post-Soviet Russian society was thrust into a new world order in which once competitors turned into unrivalled global players that neighbouring countries formed alliances with (43). The perceived betrayal from brotherly nations fed into a particular victimhood narrative that further distanced Russians from their international standing as a global superpower. In sum, the collapse of the USSR shattered the Russian population’s worldview and sense of self.  

The last two parts of the book explain the ways in which Putin’s leadership and the Kremlin-controlled media took advantage of that narrative of victimhood to manipulate the Russian population. Indeed, shame and humiliation accompanied the fall of an empire that was touted as one of the great liberators of Europe from the fascist Nazis. Amidst a period of confusion and despair, the Russian population, left to their own devices after Russian elites’ scramble for resources, became particularly enchanted by a new reassuring political figure. Former state security agent Vladimir Putin seemingly knew exactly which “hot buttons” to press in order to get Russians to play right into his hands by instrumentalizing this emotional baggage of shame and humiliation (Sharafutdinova 2020, 18). For instance, Putin carefully constructed image provided reassurance in the 1990s, which the Kremlin painted as a period of societal decay, or _likhie devianostye_, tainting Boris Yeltsin’s kleptocratic legacy. Here the title of the book begins to take its meaning with the Russian people portrayed as Alice and Putin as the Red Knight of Lewis Caroll’s famous fairy tale Through the Glass Looking-in. Jaded by the political rivalries between corrupted wealthy Russians fighting for resource monopoly that further deteriorated local economies, Russian society turned its back from a harsh reality laid out in plain sight and, by extension, their imperial history, to favour a whitewashed history based on this “chosen trauma” of an oppressive communist past (111). Through the use of state-controlled media and psychological tactics, the Kremlin effectively and successfully legitimized Putin as a strong leader in the eyes of a directionless Russian population in need of a protective figure in a world filled with moral decay. Putin’s first presidential mandate from 2000 to 2008 consisted of bringing economic stability to Russia, then turned into upholding noble traditional Russian and moral values in his second two-term mandate from 2012 to 2024. In summary, _The Red Mirror_ discusses Russian nationalism beyond the repressive political climate in Russia, dissecting the historical weight of Soviet history and the social engineering required to give meaning to an escapist form of nationalism.


### ASSESSMENT

#### Social Identity Theories
\

To start, Russian nationalism is no different than any other existing kind of patriotism that socially and symbolically binds a nation together, yet the receptivity it builds into the Russian population is one of a kind. In fact, it projects Russia as a global superpower and perpetual victim all at the same time, suffering from its own benevolence and the jealousy of its enemies. As Sharafutdinova puts it, the Russian people represent a “victimized” group that is internally insecure and seeks external validation, for the politics of recognition will not quench their desire for moral superiority as global peacemakers (145). Spanning two continents, the Russian community occupies the largest geographical territory on Earth, making it particularly impressive to maintain such a tight-knit political community. Hence, imagination is key. Anderson’s Imagined Community remains one of the foundational theories on national identities, describing this permeating sentiment of togetherness as a collective that transcends time and spatial distance. However, Anderson’s theory falls short on describing the rupture of a national identity born out of an empire and restructured piece by piece to concoct a national identity shielding its base from the \“hostile\” world and its oppressive past. Likewise, as most theories on social identity merely encompass the complexity tied to the post-Soviet Russian identity, Sharafutdinova decides to eschew Western-centric beliefs of the sorts of identities, such as the Homo Sovieticus, that were used to disparagingly define former USSR citizens (28). Taking a step back from contrived conceptions of Russian nationalism, Sharafutdinova brilliantly developed a social identity theory that mixes psychology, nationalism literature, and Russian symbolism and ontology, deciphering a heavily fantasized national identity comparable to Lewis Carroll’s Through the Glass Looking-in. Through a constructivist approach, she indicates that Russia’s brand of nationalism relies on contextual clues related to a shared, fabricated history and “vocabulary of pain” that no outsider to the Russian sphere could grasp or rationalize (96). _The Red Mirror_ recounts the imaginary tale of a national community unable to reckon with its past—and confront itself in the mirror. As implied by Sharafutdinova, Putin and Kremlin-controlled state media guides the Russian people in this alternate reality that isolates them from the rest of the world who are left in a state of confusion trying to make sense of Russia’s behaviour on the international scene. 

Additionally, Sharafutdinova demonstrates the way this insecure yet exceptional Russian identity is continually manifested and reinforced by psychological triggers ingrained in the population at all stages of life by either education, religion, mass army, or state media, permeating their everyday life. For those who get to cast their ballots at least once every four years, it is particularly illuminating to place oneself in the shoes of people who were told that their actions—however small they are—contribute to world peace as mere citizens or soldiers. Such a way of thinking is also displayed in Carroll’s tale: “She who saves a single soul, saves the universe” (1971). That degree of instrumentalization surpasses previous authoritative regimes by its cunning use of psychological wounds and modern technologies, effectively tapping into affective and cognitive structures that rally the population around one identity, one government, and one nation. Moreover, in the third part of the book, Sharafutdinova deconstructs flagrant media tactics used in news reports, shows, and political debates broadcasted on national state television which purposefully crafts a “strongman” image of President Putin. In recent years, a generational gap has been growing between those consuming traditional forms of media, including print and television, and those entering interconnected global social media platforms. To remedy such a generational separation of this imaginary path, the Kremlin has developed an arsenal of advanced media tactics to infiltrate and inject its propaganda in a relatively unregulated cyberspace. Kremlin propaganda used to fall on nations’ deaf ears, unaware of the stream of misinformation launched into digital spaces. Nonetheless, the fact has remained the same on Russian soil and abroad: “Imagination is the only weapon in the war against reality” (Carroll 1971). By virtue of its innovative analytical strategies and non-Western point of view, _The Red Mirror_ represents an avant-garde encyclopedia to the post-Soviet Russian mentality, contributing a wealth of knowledge and innovative methodology to the study of identity politics and nationalism, as well as post-Soviet studies in Western academic literature.


#### Methodology
\
_Confronting Exceptionalism_ 


Though Sharafutdinova acknowledges the history of ethnic and religious persecution in Russia, as well as the stark rural-urban divide across the country, she seems to downplay an intrinsic aspect of exceptionalism, and nationalism in general. That inevitably ties into the ego of the conflicted population whose ressentiment grows from powerlessness, spiralling into an alternate reality (Mishra 2017, 13). As much as psychological and affective triggers are involved, an exceptionalism narrative remains and falls under the scope of analysis, which leans into a biased account of grand manipulation by the Kremlin and Putin himself which propagate this doctrine of Russo-centric statism as the national ideology. In the preface, Sharafutdinova admits her bias for the misled Russian population and writes truthful and transparent explanations for the insecurity consuming the Russian community from within. 

Yet, the dominant identity that is appointed to modernize and elevate Russia in the global arena does not reflect the multiethnic character of the diverse peoples of Russia. Indeed, the “habituated dominance” of Slavic Russian people is comparable to the English folks’ long-held sense of superiority over the Scottish, Irish, and Welsh nations (Meadwell 2019). Those beliefs help justify subordination but sow discord the dominant bases its whole identity on domination. As was Russian nationalism, English nationalism entailed the construction of existential threats, such as the French or asymmetrical devolution in the Union, that were mostly exaggerated to amplify this cultish obsession with state symbols like the Westminster Parliament in England (Colley 2009, 52). The nemesis of Russia constituted multiple “others” such as the capitalist West and their Soviet communist past, which placed the country in a paradox where it went from a perpetrator to a victim.

\
_Complexity of Social Conditioning_


In a similar fashion, those shared traumatic experiences under the Soviet regimes strengthened the national bond of Russian citizens, as well as anti-Russian sentiments in former Soviet republics. In her book, Sharafutdinova carefully conveys the decisions that would lead one to lie or make self-deprecating jokes about Russia’s current state of affairs. Studies have determined that the role of ethnicity plays little influence in political attitudes and voting outcomes that favour Putin, as ethnic minorities tend to display a tendency to support Putin’s peacemaking interventions, which are symbolic reminders of the USSR’s power (Alexseev 2016, 167). Group identity in Russia is particularly salient in the realm of foreign policy, uniting people in their lived experiences in the face of a common enemy. However, Russian foreign policy and public opinion are somehow interdependent to some extent because intervention plans are self-legitimating tools utilized by the Kremlin to bolster nationalism at home (Saideman 2008, 175). That fact alone proves that meeting the “needs” of Russian people is key to maintaining legitimacy and power in Russia, as proven in the failed irredentist movement in Riga, Latvia due to disinterest among Russia’s population (185).  


Nevertheless, public opinion and state-led national polls clearly illustrate the landscape in which group identity salience functions in Russia, manifesting in the acts of the herd mentality, self-censorship, and doublethink. As Kuran argues, harsh state policies heavily restricting civic spaces conditions people into unconsciously and consciously self-regulating their action and behaviour. In a sense, Russian nationalism is built and reinforced through social conformity which encourages preference falsification by leading people to support collective beliefs contrary to one’s own in the interest of maintaining status quo (Sharafutdinova 2020, 97; Kuran 1991, 32). To conclude, _The Red Mirror_ by Gulnaz Sharafutdinova paints a comprehensive picture of the current state of nationalism in Russia where the population is pushed against a wall, presented with no other choice than to accept the best alternate reality.


\newpage


# REFERENCE LIST 

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

\
\indent Alexseev, M. A. (2016). Backing the USSR 2.0: Russia’s ethnic minorities and expansionist ethnic Russian nationalism. In P. Kolstø & H. Blakkisrud (Eds.), _The New Russian Nationalism: Imperialism, Ethnicity and Authoritarianism 2000–2015_ (pp. 160–191). Edinburgh University Press. http://www.jstor.org/stable/10.3366/j.ctt1bh2kk5.13
\
\indent Anderson, B. R. O. G. (1991). _Imagined Communities: Reflections on The Origin And Spread Of Nationalism_.
\
\indent Carroll, L. (1971). _Alice in Wonderland_. (D. J. Gray, Ed.) ([1st ed.], Ser. Norton critical editions). W. W. Norton.
\
\indent Colley, L. (2009). _Britons: Forging the Nation, 1707–1837_. Yale University Press.
\
\indent Kuran, T. (2017). _Private Truths, Public Lies: The Social Consequences of Preference Falsification_. Cambridge, MA: Harvard University Press.
\
\indent Kuran, T. (1991). Now Out of Never: The Element of Surprise in the East European Revolution of 1989. _World Politics, 44(1)_, 7–48. https://doi.org/10.2307/2010422
\
\indent Meadwell, H. (2019). “Long read: Is Brexit the English reaction to devolution?” _LSE Blog Contributions on Brexit_. https://blogs.lse.ac.uk/brexit/2019/10/10/devolution-brexit-and-english-nationalism/ 
\
\indent Saideman (2008). 8 : Findings and Implications. In _For Kin or Country: Xenophobia, Nationalism, and War_. New York Chichester, West Sussex: Columbia University Press. pp. 232–252 https://doi-org.proxy3.library.mcgill.ca/10.7312/said14478-011
\
\indent Sharafutdinova, G. (2020). _The Red Mirror_: Putin’s Leadership and Russia’s Insecure Identity. Oxford University Press.
